[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
single_line_statement_blocks = 'multi'
multiline_func_header = 'attributes_first'
contract_new_lines = false
override_spacing = false
tab_width = 4
bracket_spacing = false
int_types = 'long'
quote_style = 'double'
number_underscore = 'remove'
sort_imports = true
ignore = ['test/migration/Users_*.sol']